### ISSUE TITLE
ValueError: The condensed distance matrix must contain only finite values

### ISSUE THREAD

**Issue by therealgenna** [mhu10/scPanoView#2]
using python 3.8, just installed panoview yesterday and got this error:

```
>>> C56.RunSearching()
Percentage of cells being analyzed: 26%
Percentage of cells being analyzed: 27%
Percentage of cells being analyzed: 30%
Percentage of cells being analyzed: 31%
Percentage of cells being analyzed: 37%
Percentage of cells being analyzed: 45%
Percentage of cells being analyzed: 51%
Percentage of cells being analyzed: 54%
Percentage of cells being analyzed: 58%
Percentage of cells being analyzed: 61%
Percentage of cells being analyzed: 62%
Percentage of cells being analyzed: 67%
Percentage of cells being analyzed: 97%
Percentage of cells being analyzed: 98%
Percentage of cells being analyzed: 99%
Clusters generated 
>>> C56.OutputResult()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/gsfs12/users/CSD/zfext/env2/lib/python3.8/site-packages/PanoramicView/scPanoView.py", line 509, in OutputResult
    linkage_matrix = linkage(sim_mat,method="ward")
  File "/gpfs/gsfs12/users/CSD/zfext/env2/lib/python3.8/site-packages/scipy/cluster/hierarchy.py", line 1057, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
```

Thank you.

**Comment by therealgenna** [comment]
The above error happened when I provided the raw counts csv as an input. It is not clear what the input should be so I looked at the example PollenRaw.csv file and there the samples (columns) are normalized to sum to 1e6 (there seems to be no log-transform and no centering; all values are >=0). When I did such a normalization to my counts I did not see the error above and OutputResult() worked. Not sure though why counts matrix would behave differently ...
